version: '3'
services:

  influx:
    image: influxdb:alpine
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecret
    ## uncomment to store the data outside the container
    #volumes:
    #  - ./influxdata:/var/lib/influxdb


  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-datasource.yaml:/usr/share/grafana/conf/datasources/influxdb.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influx
  
  telegraf:
    image: telegraf
    depends_on:
      - influx
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf